# Generated by Django 4.1.4 on 2022-12-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
